# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
#require_relative '../reactnative/node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../reactnative/node_modules/react-native/scripts/react_native_pods'

target 'ReactNativeIntegration' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_react_native!(:path => '../reactnative/node_modules/react-native/')
  pod 'RNGestureHandler', :path => '../reactnative/node_modules/react-native-gesture-handler'
  pod 'react-native-safe-area-context', :path => '../reactnative/node_modules/react-native-safe-area-context'
  # pod 'React', :path => '../reactnative/node_modules/react-native/'
  # pod 'React-Core', :path => '../reactnative/node_modules/react-native'
  # pod 'React-DevSupport', :path => '../reactnative/node_modules/react-native/React'
  # pod 'React-fishhook', :path => '../reactnative/node_modules/react-native/Libraries/fishhook'
  # pod 'React-RCTActionSheet', :path => '../reactnative/node_modules/react-native/Libraries/ActionSheetIOS'
  # pod 'React-RCTAnimation', :path => '../reactnative/node_modules/react-native/Libraries/NativeAnimation'
  # pod 'React-RCTBlob', :path => '../reactnative/node_modules/react-native/Libraries/Blob'
  # pod 'React-RCTImage', :path => '../reactnative/node_modules/react-native/Libraries/Image'
  # pod 'React-RCTLinking', :path => '../reactnative/node_modules/react-native/Libraries/LinkingIOS'
  # pod 'React-RCTNetwork', :path => '../reactnative/node_modules/react-native/Libraries/Network'
  # pod 'React-RCTSettings', :path => '../reactnative/node_modules/react-native/Libraries/Settings'
  # pod 'React-RCTText', :path => '../reactnative/node_modules/react-native/Libraries/Text'
  # pod 'React-RCTVibration', :path => '../reactnative/node_modules/react-native/Libraries/Vibration'
  # pod 'React-RCTWebSocket', :path => '../reactnative/node_modules/react-native/Libraries/WebSocket'

  # pod 'React-cxxreact', :path => '../reactnative/node_modules/react-native/ReactCommon/cxxreact'
  # pod 'React-jsi', :path => '../reactnative/node_modules/react-native/ReactCommon/jsi'
  # pod 'React-jsiexecutor', :path => '../reactnative/node_modules/react-native/ReactCommon/jsiexecutor'
  # pod 'React-jsinspector', :path => '../reactnative/node_modules/react-native/ReactCommon/jsinspector'
  # pod 'Yoga', :path => '../reactnative/node_modules/react-native/ReactCommon/yoga'

  # pod 'DoubleConversion', :podspec => '../reactnative/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'glog', :podspec => '../reactnative/node_modules/react-native/third-party-podspecs/glog.podspec'
  # pod 'Folly', :podspec => '../reactnative/node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'ReactNativeIntegrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeIntegrationUITests' do
    # Pods for testing
  end

end
