platform :ios, '10.0'
require_relative '../reactnative/node_modules/react-native/scripts/react_native_pods'

target 'ReactNativeIntegration' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_react_native!(:path => '../reactnative/node_modules/react-native/')
  pod 'RNGestureHandler', :path => '../reactnative/node_modules/react-native-gesture-handler'
  pod 'react-native-safe-area-context', :path => '../reactnative/node_modules/react-native-safe-area-context'

  target 'ReactNativeIntegrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeIntegrationUITests' do
    # Pods for testing
  end

end
